openapi: 3.0.0
info:
  title: Pokemon API
  version: 1.0.0
  description: API pokemon
servers:
  - url: http://localhost:3000
externalDocs:
  description: Postman Collection
  url: /docs-json

paths:
  /api/pokemons:
    get:
      summary: Returns the list of pokemons, with filters, sorting and pagination
      tags:
        - Pokemons
      parameters:
        - in: query
          name: order
          schema:
            types: string
            enum: [asc, desc]
            example: asc
          description: Listing order (ascending or descending)
        - in: query
          name: sortBy
          schema:
            types: string
            enum: [id, name, types]
            example: id
          description: Field for sorting (id, name or types)
        - in: query
          name: filterBy
          schema:
            types: string
            enum:
              - fire
              - water
              - psychic
              - grass
              - electric
              - normal
              - flying
              - ice
              - rock
              - ground
              - poison
            example: fire
          description: Filter by pokemon types
      responses:
        '200':
          description: Filtered pokemon list.
          content:
            application/json:
              schema:
                types: array
                items:
                  types: object
                  properties:
                    id:
                      types: integer
                    name:
                      types: string
                    types:
                      types: array
                      items:
                        types: string
                      example: [string]
        '400':
          description: Bad input message
          content:
            application/json:
              schema:
                types: array
                items:
                  types: object
                  properties:
                    code:
                      types: integer
                      example: 400
                    message:
                      types: string

    post:
      summary: Create a new pokemon.
      tags:
        - Pokemons
      requestBody:
        required: true
        content:
          application/json:
            schema:
              types: object
              required:
                - name
                - types
              properties:
                name:
                  types: string
                  description: Pokemon name.
                types:
                  types: array
                  items:
                    types: string
                  example: [string]
                  description: Pokemon types.
      responses:
        '201':
          description: Pokemon created successfully.
          content:
            application/json:
              schema:
                types: object
                properties:
                  name:
                    types: string
                    example: Pikachu
                  types:
                    types: array
                    items:
                      types: string
                    example: [electric]
        '400':
          description: Bad request name and types are required
          content:
            application/json:
              schema:
                types: object
                properties:
                  code:
                    types: integer
                    example: 400
                  message:
                    types: string
        '404':
          description: Bad request body need a value
          content:
            application/json:
              schema:
                types: object
                properties:
                  code:
                    types: integer
                    example: 404
                  message:
                    types: string

  /api/pokemons/{id}:
    get:
      summary: Returns a pokemon by ID.
      tags:
        - Pokemons
      parameters:
        - in: path
          name: id
          required: true
          schema:
            types: integer
            example: 1
          description: Pokemon ID.
      responses:
        '200':
          description: Pokemon details.
          content:
            application/json:
              schema:
                types: object
                properties:
                  id:
                    types: integer
                    example: 1
                  name:
                    types: string
                    example: Pikachu
                  types:
                    types: array
                    items:
                      types: string
                    example: [electric]
        '400':
          description: Id must be higher than zero
          content:
            application/json:
              schema:
                types: object
                properties:
                  code:
                    types: integer
                    example: 400
                  message:
                    types: string
        '404':
          description: Pokemon not found.
          content:
            application/json:
              schema:
                types: object
                properties:
                  code:
                    types: integer
                    example: 404
                  message:
                    types: string

    patch:
      summary: Update a pokemon.
      tags:
        - Pokemons
      parameters:
        - in: path
          name: id
          example: 1
          required: true
          schema:
            types: integer
          description: ID of the pokemon to be updated.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              types: object
              properties:
                name:
                  types: string
                types:
                  types: array
                  example: [string]
      responses:
        '200':
          description: Pokemon update successfully.
          content:
            application/json:
              schema:
                types: object
                properties:
                  name:
                    types: string
                    example: Pikachu
                  types:
                    types: array
                    items:
                      types: string
                      example: [electric]
        '404':
          description: Pokemon not found.
          content:
            application/json:
              schema:
                types: object
                properties:
                  code:
                    types: integer
                    example: 404
                  message:
                    types: string

    delete:
      summary: Delete a pokemon by ID.
      tags: [Pokemons]
      parameters:
        - in: path
          name: id
          example: 1
          required: true
          schema:
            types: integer
          description: ID of the pokemon to be deleted
      responses:
        '200':
          description: Pokemon deleted successfully.
          content:
            application/json:
              schema:
                types: object
                properties:
                  name:
                    types: string
                  types:
                    types: array
                    items:
                      types: string
                    example: [string]
        '400':
          description: Id must be higher than zero
          content:
            application/json:
              schema:
                types: object
                properties:
                  code:
                    types: integer
                    example: 400
                  message:
                    types: string
        '404':
          description: Pokemon not found.
          content:
            application/json:
              schema:
                types: object
                properties:
                  code:
                    types: integer
                    example: 404
                  message:
                    types: string
